// Auto-generated by Supabase CLI: npx supabase gen types typescript
// Run this command after setting up your database schema to regenerate.

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
